var majorArcana = [
    {
        name: "The Fool",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Magician",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The High Priestess",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Empress",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Emperor",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Heirophant",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Lovers",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Chariot",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "Strength",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Hermit",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "Wheel of Fortune",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "Justice",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Hanged Man",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "Death",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "Temperance",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Devil",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Tower",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Star",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Moon",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The Sun",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "Judgment",
        past: ,
        present: ,
        future: ,
        image: ,
    },
    {
        name: "The World",
        past: ,
        present: ,
        future: ,
        image: ,
    },
]